### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by shuvashish76** [shub39/Grit#2]
Hello, would you consider publishing the app on F-Droid please?
Documentation : https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md

**Comment by shub39** [comment]
Tried but repro failed. It's there now and shows up in fdroid clients

**Comment by shuvashish76** [comment]
Thanks, feel free to use their badge : https://gitlab.com/fdroid/artwork/-/blob/master/badge/README.md
